In [2]:
import pandas as pd


In [4]:
import numpy as np

In [6]:
data = pd.read_csv("diabetes.csv", delimiter = ',')

In [8]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
x = data.iloc[:,:-1]

In [18]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [21]:
y = data.iloc[:,-1]

In [23]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [25]:
data.shape

(768, 9)

In [29]:
dataset = np.genfromtxt('diabetes.csv', delimiter = ',', skip_header = True)

In [32]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [41]:
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})

In [43]:
dataset

array([[ 6.0,  148.0,  72.0, ...,  0.6,  50.0,  1.0],
       [ 1.0,  85.0,  66.0, ...,  0.4,  31.0,  0.0],
       [ 8.0,  183.0,  64.0, ...,  0.7,  32.0,  1.0],
       ...,
       [ 5.0,  121.0,  72.0, ...,  0.2,  30.0,  0.0],
       [ 1.0,  126.0,  60.0, ...,  0.3,  47.0,  1.0],
       [ 1.0,  93.0,  70.0, ...,  0.3,  23.0,  0.0]])

In [45]:
x = dataset[:,:-1]

In [47]:
x

array([[ 6.0,  148.0,  72.0, ...,  33.6,  0.6,  50.0],
       [ 1.0,  85.0,  66.0, ...,  26.6,  0.4,  31.0],
       [ 8.0,  183.0,  64.0, ...,  23.3,  0.7,  32.0],
       ...,
       [ 5.0,  121.0,  72.0, ...,  26.2,  0.2,  30.0],
       [ 1.0,  126.0,  60.0, ...,  30.1,  0.3,  47.0],
       [ 1.0,  93.0,  70.0, ...,  30.4,  0.3,  23.0]])

In [49]:
y = dataset[:,-1]

In [51]:
y

array([ 1.0,  0.0,  1.0,  0.0,  1.0,  0.0,  1.0,  0.0,  1.0,  1.0,  0.0,
        1.0,  0.0,  1.0,  1.0,  1.0,  1.0,  1.0,  0.0,  1.0,  0.0,  0.0,
        1.0,  1.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0,  1.0,
        0.0,  1.0,  0.0,  0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
        0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,  1.0,  0.0,
        1.0,  0.0,  0.0,  0.0,  1.0,  0.0,  1.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,  0.0,
        1.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        1.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,
        1.0,  1.0,  0.0,  0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0,  1.0,
        0.0,  0.0,  0.0,  1.0,  1.0,  0.0,  0.0,  1.0,  1.0,  1.0,  1.0,
        1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0

In [58]:
!pip install keras

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [63]:
model = Sequential()
model.add(Dense(1,input_dim = 8, activation ='sigmoid'))

In [66]:
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])

In [72]:
model.fit(x =x, y =y, epochs = 512, verbose = 1)

Epoch 1/512
24/24 [==============================] - 0s 2ms/step - loss: 0.4903 - accuracy: 0.7695
Epoch 2/512
24/24 [==============================] - 0s 2ms/step - loss: 0.4897 - accuracy: 0.7708
Epoch 3/512
24/24 [==============================] - 0s 2ms/step - loss: 0.4911 - accuracy: 0.7734
Epoch 4/512
24/24 [==============================] - 0s 3ms/step - loss: 0.4875 - accuracy: 0.7708
Epoch 5/512
24/24 [==============================] - 0s 2ms/step - loss: 0.4890 - accuracy: 0.7682
Epoch 6/512
24/24 [==============================] - 0s 3ms/step - loss: 0.4918 - accuracy: 0.7630
Epoch 7/512
24/24 [==============================] - 0s 3ms/step - loss: 0.4902 - accuracy: 0.7617
Epoch 8/512
24/24 [==============================] - 0s 3ms/step - loss: 0.4880 - accuracy: 0.7669
Epoch 9/512
24/24 [==============================] - 0s 2ms/step - loss: 0.4846 - accuracy: 0.7734
Epoch 10/512
24/24 [==============================] - 0s 3ms/step - loss: 0.4818 - accuracy: 0.7643
Epoch 11/

In [74]:
print(y[:5])

[ 1.0  0.0  1.0  0.0  1.0]


In [76]:
pred = model.predict(x)

24/24 [==============================] - 7s 2ms/step


In [78]:
print(pred[:5].T)

[[ 0.8  0.1  0.8  0.1  0.9]]
